### ISSUE TITLE
[Feature Request] - Remove reference results from ratio plots

### ISSUE THREAD

**Issue by Radiation-Transport** [JADE-V-V/JADE-WEB-APP#28]
**Describe the bug**
In the default representation of the ITER_CYL_SDDR plot (the ratio plot) the reference inserted library is the one appearing (not shadowed). This should not be the case.
![image](https://github.com/user-attachments/assets/ddcc5f5b-8313-4c2c-b4b0-f180f3ceb34c)

**To Reproduce**
1. use ITER_CYL_SDDR plot
2. ask for dose rate
3. See error

**Expected behavior**
I would expect to see the library which is not the referenced to be plotted.

**Desktop (please complete the following information):**
Web based application.

**Comment by dodu94** [comment]
Hi Marco, this is the intended behaviour. For how the webapp it is structured, reference values are still plotted because they are needed when switching to the absolute value plot. Implementing logic that removes that only for ratio plot may be not worth it. If you are really bothered by it, we can ask Marta to have a look.

**Comment by Radiation-Transport** [comment]
Ok, understood. No need to modify that so but I had to think twice why we had not difference (as I knew the results). I close the issue.
